### ISSUE TITLE
Milestone 2 Issues

### ISSUE THREAD

**Issue by aimirza** [UBC-MDS/DSCI_522_Alberta-Oil-Spills#36]
- [x] Decision tree figure is far too small to be useful. See [this comment ](https://github.com/UBC-MDS/DSCI_522_Alberta-Oil-Spills/issues/31#issuecomment-444963237)on the previous issue. 
- [x] You need to have some discussion on every table and figure. Can you discuss/interpret the decison tree in fiture 7? 
- [x] You need a unit test for the function `save_and_show_decision_tree`
- [x] Show the actual importance value of each feature in table 4 so that the reader can have some understanding of the magnitude of importance relative to the other features. 

- Why not add [results/depth_compare](https://github.com/UBC-MDS/DSCI_522_Alberta-Oil-Spills/blob/V3.0/results/depth_compare.png) to the report?

**Comment by huijuechen** [comment]
- Updated decision tree figure to be readable.
- Added interpretation of the decision tree in figure 7 (now Figure 8)
- Added unit test for the function save_and_show_decision_tree
- Added Gini importance value of each feature in table 4
- Added results/depth_compare to the report (as new Figure 7), interpreted on the figure, and related to our hyperparameter setting of the decision tree
